// Generated by CoffeeScript 1.6.3
var Parse;

Parse = require('node-parse-api').Parse;

exports.APP_ID = 'pIvOTKXjFxWRgR5IqX4z0kYMKIHKl5Uq74FNHGNU';

exports.MASTER_KEY = '8SoYL0XEnVhJ90K5th8hcNFW6s2murr0UB9EpHBm';

exports.parseDb = new Parse(exports.APP_ID, exports.MASTER_KEY);

exports.name = function(req, res) {
  return res.json({
    name: 'Bob'
  });
};

exports.events = function(req, res) {
  return exports.parseDb.findMany('Events', {}, function(err, response) {
    return res.json(response.results);
  });
};

exports.slides = function(req, res) {
  return exports.parseDb.findMany('Slides', {}, function(err, response) {
    return res.json(response.results);
  });
};

exports.features = function(req, res) {
  return exports.parseDb.findMany('Features', {}, function(err, response) {
    return res.json(response.results);
  });
};
