// Generated by CoffeeScript 1.4.0

exports.index = function(req, res) {
  return res.render('index.html');
};

exports.partials = function(req, res) {
  var name;
  name = req.params.name;
  return res.render('partials/' + name + '.html');
};
